begin;
select plan(21);
select has_table('public','notification_outbox','generic notification outbox exists');
select col_is_pk('public','notification_outbox','id','outbox has identity primary key');
select col_type_is('public','notification_outbox','aggregate_id','uuid','aggregate identity is UUID');
select col_type_is('public','notification_outbox','payload','jsonb','payload is symbolic JSON');
select table_privs_are('public','notification_outbox','authenticated',array['SELECT'],'staff only receives table read grant');
select function_privs_are('public','claim_notification_outbox',array['integer'],'service_role',array['EXECUTE'],'service may claim');
select function_privs_are('public','claim_notification_outbox',array['integer'],'authenticated',array[]::text[],'authenticated cannot claim');
select function_privs_are('public','complete_notification_outbox',array['bigint','text','text','uuid','integer'],'anon',array[]::text[],'anon cannot complete');
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
do $$declare a bigint;b bigint;begin a:=public.enqueue_notification_outbox('order','11111111-1111-4111-8111-111111111111','order_created','22222222-2222-4222-8222-222222222222',null,null,'web','{"message_key":"order_created"}');b:=public.enqueue_notification_outbox('order','11111111-1111-4111-8111-111111111111','order_created','22222222-2222-4222-8222-222222222222',null,null,'web','{"message_key":"order_created"}');perform set_config('test.first_ids',a::text||':'||b::text,false);perform public.enqueue_notification_outbox('order','11111111-1111-4111-8111-111111111111','order_created','22222222-2222-4222-8222-222222222222',null,null,'telegram','{"message_key":"order_created"}');end$$;
reset role;
select is(split_part(current_setting('test.first_ids'),':',1),split_part(current_setting('test.first_ids'),':',2),'same event and destination is idempotent');
select is((select count(*)::integer from public.notification_outbox where event_id='22222222-2222-4222-8222-222222222222'),2,'idempotent web and independent telegram rows coexist');
select isnt((select min(id) from public.notification_outbox),(select max(id) from public.notification_outbox),'second destination has independent identity');
select is((select count(distinct channel)::integer from public.notification_outbox where event_id='22222222-2222-4222-8222-222222222222'),2,'two destination channels remain isolated');
select throws_ok($$insert into public.notification_outbox(aggregate_type,aggregate_id,event_type,event_id,channel,payload,delivery_key) values('order','33333333-3333-4333-8333-333333333333','refund_completed','44444444-4444-4444-8444-444444444444','web','{"message_key":"refund_completed"}','44444444-4444-4444-8444-444444444444:web')$$,'23514',null,'aggregate and event must be compatible');
select throws_ok($$insert into public.notification_outbox(aggregate_type,aggregate_id,event_type,event_id,channel,payload,delivery_key) values('order','33333333-3333-4333-8333-333333333333','order_created','55555555-5555-4555-8555-555555555555','web','{"message_key":"order_created","meta":{"email":"private@example.test"}}','55555555-5555-4555-8555-555555555555:web')$$,'23514',null,'nested or unknown payload fields are rejected');
select throws_ok($$insert into public.notification_outbox(aggregate_type,aggregate_id,event_type,event_id,channel,payload,delivery_key) values('order','33333333-3333-4333-8333-333333333333','order_created','66666666-6666-4666-8666-666666666666','web','{"message_key":"order_created","status":{"name":"private"}}','66666666-6666-4666-8666-666666666666:web')$$,'23514',null,'symbolic payload values must be strings');
set local role service_role;
do $$declare c record;begin select * into c from public.claim_notification_outbox(60);perform set_config('test.claim_id',c.id::text,false);perform set_config('test.claim_token',c.lease_token::text,false);perform set_config('test.claim_attempt',c.attempt::text,false);end$$;
reset role;
select ok(current_setting('test.claim_id')::bigint>0,'claim returns a delivery with a lease token');
set local role service_role;
select ok(public.complete_notification_outbox(current_setting('test.claim_id')::bigint,'retryable','private@example.test',current_setting('test.claim_token')::uuid,current_setting('test.claim_attempt')::integer),'fenced retry completion succeeds');
reset role;
select is((select status||':'||attempts::text||':'||last_error from public.notification_outbox where id=current_setting('test.claim_id')::bigint),'pending:1:operation_failed','retry clears lease and maps unknown errors to a fixed token');
update public.notification_outbox set next_attempt_at=now() where id=current_setting('test.claim_id')::bigint;
set local role service_role;
do $$declare c record;begin select * into c from public.claim_notification_outbox(60);perform set_config('test.next_token',c.lease_token::text,false);perform set_config('test.next_attempt',c.attempt::text,false);end$$;
select ok(not public.complete_notification_outbox(current_setting('test.claim_id')::bigint,'success',null,current_setting('test.claim_token')::uuid,current_setting('test.claim_attempt')::integer),'stale token and attempt cannot complete a newer lease');
select ok(public.complete_notification_outbox(current_setting('test.claim_id')::bigint,'permanent','invalid_destination',current_setting('test.next_token')::uuid,current_setting('test.next_attempt')::integer),'current lease can dead-letter independently');
reset role;
select is((select status from public.notification_outbox where id=current_setting('test.claim_id')::bigint),'dead_letter','permanent disposition is dead-lettered');
select * from finish();
rollback;
