alter table public.payment_proof_outbox add column status text not null default 'pending' check(status in('pending','claimed','completed','dead_letter')),add column attempts integer not null default 0,add column next_attempt_at timestamptz not null default now(),add column claimed_until timestamptz,add column completed_at timestamptz,add column last_error text,add column delivery_key uuid not null default gen_random_uuid();
create unique index payment_proof_outbox_delivery_key on public.payment_proof_outbox(delivery_key);
alter table public.payment_proofs drop constraint payment_proofs_status_check;
alter table public.payment_proofs add constraint payment_proofs_status_check check(status in('received','identity_pending','processing','review','admitted','quarantined','purging','duplicate','purged'));
create function public.claim_payment_proof_maintenance(p_lease_seconds integer default 60) returns jsonb language plpgsql security definer set search_path='' as $$declare o public.payment_proof_outbox%rowtype;p public.payment_proofs%rowtype;begin
 if coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception using errcode='42501',message='PAYMENT_PROOF_SERVICE_ROLE_REQUIRED';end if;
 select * into o from public.payment_proof_outbox where status in('pending','claimed') and next_attempt_at<=now() and(status='pending' or claimed_until<=now()) order by id for update skip locked limit 1;
 if found then update public.payment_proof_outbox set status='claimed',claimed_until=now()+make_interval(secs=>greatest(10,least(p_lease_seconds,300))),attempts=attempts+1 where id=o.id returning * into o;return jsonb_build_object('kind','outbox','id',o.id,'channel',o.channel,'payload',o.payload,'delivery_key',o.delivery_key,'attempt',o.attempts);end if;
 select * into p from public.payment_proofs where status='quarantined' and purge_after<=now() order by purge_after,id for update skip locked limit 1;
 if found then update public.payment_proofs set status='purging',updated_at=now() where id=p.id;return jsonb_build_object('kind','purge','id',p.id,'original_key',p.original_storage_key,'preview_key',p.preview_storage_key);end if;return null;end$$;
create function public.complete_payment_proof_maintenance(p_kind text,p_id text,p_success boolean,p_error text default null) returns boolean language plpgsql security definer set search_path='' as $$declare n integer;begin
 if coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception using errcode='42501',message='PAYMENT_PROOF_SERVICE_ROLE_REQUIRED';end if;
 if p_kind='outbox' then update public.payment_proof_outbox set status=case when p_success then 'completed' when attempts>=5 then 'dead_letter' else 'pending' end,completed_at=case when p_success then now() end,claimed_until=null,last_error=left(p_error,500),next_attempt_at=now()+make_interval(secs=>least(3600,30*(2^greatest(attempts-1,0)))) where id=p_id::bigint and status='claimed';get diagnostics n=row_count;return n=1;end if;
 if p_kind='purge' then update public.payment_proofs set status=case when p_success then 'purged' else 'quarantined' end,preview_storage_key=case when p_success then null else preview_storage_key end,updated_at=now(),purge_after=case when p_success then purge_after else now()+interval '1 hour' end where id=p_id::uuid and status='purging';get diagnostics n=row_count;if n=1 and p_success then insert into public.payment_proof_events(proof_id,event_type,source,previous_status,result_status)values(p_id::uuid,'purged','worker','quarantined','purged');end if;return n=1;end if;return false;end$$;
revoke all on function public.claim_payment_proof_maintenance(integer),public.complete_payment_proof_maintenance(text,text,boolean,text) from public,anon,authenticated;grant execute on function public.claim_payment_proof_maintenance(integer),public.complete_payment_proof_maintenance(text,text,boolean,text) to service_role;
create function public.dead_letter_payment_proof_outbox(p_id bigint,p_error text) returns boolean language plpgsql security definer set search_path='' as $$declare n integer;begin if coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception using errcode='42501',message='PAYMENT_PROOF_SERVICE_ROLE_REQUIRED';end if;update public.payment_proof_outbox set status='dead_letter',claimed_until=null,last_error=left(p_error,500) where id=p_id and status='claimed';get diagnostics n=row_count;return n=1;end$$;revoke all on function public.dead_letter_payment_proof_outbox(bigint,text) from public,anon,authenticated;grant execute on function public.dead_letter_payment_proof_outbox(bigint,text) to service_role;
