-- Bucket-aware reconciliation for legacy objects. It never attributes an object
-- heuristically: referenced objects are protected, unreferenced ones require
-- explicit approval before Storage deletion.
create table public.storage_orphan_reconciliations(
 id uuid primary key default gen_random_uuid(),bucket_id text not null check(bucket_id in('chat-midias','payment-proofs')),
 object_path text not null,object_created_at timestamptz not null,discovered_at timestamptz not null,
 reference_status text not null check(reference_status in('referenced','unreferenced')),
 status text not null default 'pending' check(status in('pending','approved','claimed','completed','protected','failed')),
 approved_by uuid references auth.users(id),approved_at timestamptz,claim_token uuid,attempts int not null default 0,last_error text,completed_at timestamptz,
 unique(bucket_id,object_path)
);
revoke all on public.storage_orphan_reconciliations from public,anon,authenticated;
create or replace function public.storage_orphan_is_referenced(p_bucket text,p_path text) returns boolean language sql security definer set search_path='' as $$
 select case when p_bucket='chat-midias' then exists(select 1 from public.mensagens where url_anexo=p_path) or exists(select 1 from public.comprovantes where url_arquivo=p_path)
 when p_bucket='payment-proofs' then exists(select 1 from public.payment_proofs where original_storage_key=p_path or preview_storage_key=p_path)
 else true end $$;
create or replace function public.registrar_reconciliacao_storage_legacy(p_bucket_id text,p_object_path text,p_object_created_at timestamptz,p_scan_at timestamptz) returns uuid language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); ref boolean; id uuid; begin
 if actor is null or not public.tem_funcoes(array['admin'::public.tipo_funcao,'supervisor'::public.tipo_funcao]) then raise exception using errcode='42501',message='USUARIO_NAO_AUTORIZADO';end if;
 if p_bucket_id not in('chat-midias','payment-proofs') or nullif(p_object_path,'') is null or p_object_created_at>p_scan_at then raise exception using errcode='22023',message='CANDIDATO_ORFAO_INVALIDO';end if;
 ref:=public.storage_orphan_is_referenced(p_bucket_id,p_object_path);
 insert into public.storage_orphan_reconciliations(bucket_id,object_path,object_created_at,discovered_at,reference_status,status) values(p_bucket_id,p_object_path,p_object_created_at,p_scan_at,case when ref then'referenced'else'unreferenced'end,case when ref or p_scan_at-p_object_created_at<interval'24 hours'then'protected'else'pending'end)
 on conflict(bucket_id,object_path) do update set object_created_at=excluded.object_created_at,discovered_at=excluded.discovered_at,reference_status=excluded.reference_status,status=case when storage_orphan_reconciliations.status in('completed','claimed')then storage_orphan_reconciliations.status else excluded.status end returning storage_orphan_reconciliations.id into id;return id;end $$;
create or replace function public.aprovar_reconciliacao_storage_legacy(p_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid();begin if actor is null or not public.tem_funcoes(array['admin'::public.tipo_funcao,'supervisor'::public.tipo_funcao])then raise exception using errcode='42501',message='USUARIO_NAO_AUTORIZADO';end if;update public.storage_orphan_reconciliations set status='approved',approved_by=actor,approved_at=now() where id=p_id and status in('pending','failed') and reference_status='unreferenced';return found;end $$;
create or replace function public.reivindicar_reconciliacao_storage_legacy(p_id uuid) returns table(id uuid,bucket_id text,object_path text,claim_token uuid) language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid();r public.storage_orphan_reconciliations%rowtype;t uuid:=gen_random_uuid();begin if actor is null or not public.tem_funcoes(array['admin'::public.tipo_funcao,'supervisor'::public.tipo_funcao])then raise exception using errcode='42501',message='USUARIO_NAO_AUTORIZADO';end if;select * into r from public.storage_orphan_reconciliations where storage_orphan_reconciliations.id=p_id and status in('approved','failed') for update skip locked;if not found then return;end if;if public.storage_orphan_is_referenced(r.bucket_id,r.object_path) then update public.storage_orphan_reconciliations set status='protected',reference_status='referenced' where id=r.id;return;end if;update public.storage_orphan_reconciliations set status='claimed',claim_token=t,attempts=attempts+1 where id=r.id;return query select r.id,r.bucket_id,r.object_path,t;end $$;
create or replace function public.finalizar_reconciliacao_storage_legacy(p_id uuid,p_token uuid,p_ok boolean,p_error text default null) returns boolean language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid();begin if actor is null or not public.tem_funcoes(array['admin'::public.tipo_funcao,'supervisor'::public.tipo_funcao])then raise exception using errcode='42501',message='USUARIO_NAO_AUTORIZADO';end if;update public.storage_orphan_reconciliations set status=case when p_ok then'completed'else'failed'end,completed_at=case when p_ok then now()else null end,last_error=case when p_ok then null else coalesce(nullif(p_error,''),'STORAGE_DELETE_FAILED')end,claim_token=null where id=p_id and status='claimed'and claim_token=p_token;return found;end $$;
revoke all on function public.registrar_reconciliacao_storage_legacy(text,text,timestamptz,timestamptz),public.aprovar_reconciliacao_storage_legacy(uuid),public.reivindicar_reconciliacao_storage_legacy(uuid),public.finalizar_reconciliacao_storage_legacy(uuid,uuid,boolean,text) from public,anon,service_role;grant execute on function public.registrar_reconciliacao_storage_legacy(text,text,timestamptz,timestamptz),public.aprovar_reconciliacao_storage_legacy(uuid),public.reivindicar_reconciliacao_storage_legacy(uuid),public.finalizar_reconciliacao_storage_legacy(uuid,uuid,boolean,text) to authenticated;
