-- Phase  durable supervisor inbox delivery, separate than customer-channel outbox.
create table public.accounts_receivable_alert_deliveries(
 id bigint generated always as identity primary key,alert_id uuid not null references public.accounts_receivable_alerts(id),recipient_id uuid not null references auth.users(id),
 status text not null default 'pending' check(status in('pending','claimed','delivered','dead_letter')),attempts integer not null default 0 check(attempts>=0),max_attempts integer not null default 8 check(max_attempts between 1 and 20),
 lease_token uuid,claimed_until timestamptz,next_attempt_at timestamptz not null default now(),delivered_at timestamptz,dead_lettered_at timestamptz,last_error text check(last_error is null or last_error in('recipient_unavailable','delivery_failed')),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(alert_id,recipient_id),
 check((status='claimed')=(lease_token is not null and claimed_until is not null))
);
alter table public.accounts_receivable_alert_deliveries enable row level security;revoke all on public.accounts_receivable_alert_deliveries from public,anon,authenticated;grant select on public.accounts_receivable_alert_deliveries to authenticated;
create policy receivable_alert_delivery_own_read on public.accounts_receivable_alert_deliveries for select to authenticated using(recipient_id=auth.uid() and public.tem_funcoes(array['admin'::public.tipo_funcao,'supervisor'::public.tipo_funcao]));
create function public.enqueue_receivable_alert_deliveries() returns trigger language plpgsql security definer set search_path='' as $$begin
 insert into public.accounts_receivable_alert_deliveries(alert_id,recipient_id) select new.id,p.id from public.perfis p where p.ativo and p.funcao in('admin','supervisor') on conflict(alert_id,recipient_id) do nothing;return new;end$$;
create trigger enqueue_receivable_alert_deliveries after insert on public.accounts_receivable_alerts for each row execute function public.enqueue_receivable_alert_deliveries();
insert into public.accounts_receivable_alert_deliveries(alert_id,recipient_id) select a.id,p.id from public.accounts_receivable_alerts a cross join public.perfis p where p.ativo and p.funcao in('admin','supervisor') on conflict(alert_id,recipient_id) do nothing;
create function public.claim_receivable_alert_delivery(p_lease_seconds integer default 60) returns table(id bigint,alert_id uuid,recipient_id uuid,event_type text,payload jsonb,attempt integer,lease_token uuid) language plpgsql security definer set search_path='' as $$declare v public.accounts_receivable_alert_deliveries%rowtype;begin
 if coalesce(auth.jwt()->>'role','')<>'service_role' or auth.uid() is not null then raise exception using errcode='42501',message='RECEIVABLE_ALERT_SERVICE_ROLE_REQUIRED';end if;if p_lease_seconds not between 10 and 300 then raise exception using errcode='22023',message='RECEIVABLE_ALERT_LEASE_INVALID';end if;
 select * into v from public.accounts_receivable_alert_deliveries d where (d.status='pending' and d.next_attempt_at<=now()) or(d.status='claimed' and d.claimed_until<=now()) order by d.id for update skip locked limit 1;if not found then return;end if;
 if v.status='claimed' and v.attempts>=v.max_attempts then update public.accounts_receivable_alert_deliveries set status='dead_letter',lease_token=null,claimed_until=null,dead_lettered_at=now(),updated_at=now() where accounts_receivable_alert_deliveries.id=v.id;return;end if;
 update public.accounts_receivable_alert_deliveries set status='claimed',attempts=attempts+1,lease_token=gen_random_uuid(),claimed_until=now()+make_interval(secs=>p_lease_seconds),updated_at=now() where accounts_receivable_alert_deliveries.id=v.id returning * into v;
 return query select v.id,v.alert_id,v.recipient_id,a.event_type,a.payload,v.attempts,v.lease_token from public.accounts_receivable_alerts a where a.id=v.alert_id;end$$;
create function public.complete_receivable_alert_delivery(p_id bigint,p_disposition text,p_error text,p_lease_token uuid,p_attempt integer) returns boolean language plpgsql security definer set search_path='' as $$declare v_error text;begin
 if coalesce(auth.jwt()->>'role','')<>'service_role' or auth.uid() is not null then raise exception using errcode='42501',message='RECEIVABLE_ALERT_SERVICE_ROLE_REQUIRED';end if;if p_disposition not in('success','retryable','permanent') then raise exception using errcode='22023',message='RECEIVABLE_ALERT_DISPOSITION_INVALID';end if;v_error:=case when p_disposition='success' then null when p_error in('recipient_unavailable','delivery_failed') then p_error else 'delivery_failed' end;
 update public.accounts_receivable_alert_deliveries set status=case when p_disposition='success' then 'delivered' when p_disposition='permanent' or attempts>=max_attempts then 'dead_letter' else 'pending' end,delivered_at=case when p_disposition='success' then now() end,dead_lettered_at=case when p_disposition='permanent' or(p_disposition='retryable' and attempts>=max_attempts) then now() end,lease_token=null,claimed_until=null,last_error=v_error,next_attempt_at=case when p_disposition='retryable' and attempts<max_attempts then now()+make_interval(secs=>least(3600,30*(2^greatest(attempts-1,0)))) else next_attempt_at end,updated_at=now() where id=p_id and status='claimed' and lease_token=p_lease_token and attempts=p_attempt;return found;end$$;
revoke all on function public.claim_receivable_alert_delivery(integer),public.complete_receivable_alert_delivery(bigint,text,text,uuid,integer) from public,anon,authenticated;grant execute on function public.claim_receivable_alert_delivery(integer),public.complete_receivable_alert_delivery(bigint,text,text,uuid,integer) to service_role;
