import {beforeEach,describe,expect,it,vi} from 'vitest'
const m=vi.hoisted(()=>({admin:vi.fn(),rag:vi.fn(),attach:vi.fn(),prompt:vi.fn(),config:vi.fn(),global:vi.fn(),hours:vi.fn(),contact:vi.fn(),resolve:vi.fn(),normalize:vi.fn(),actionRouter:vi.fn()}))
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:m.admin}));vi.mock('@/lib/ai/openrouter',()=>({processarRagPipeline:m.rag}));vi.mock('@/lib/sofia/inbound-batch-producer',()=>({attachPersistedSofiaInboundMessage:m.attach}));vi.mock('@/lib/whatsapp/gateways/catalog-gateway',()=>({enviarPromptCatalogoWhatsApp:m.prompt}));vi.mock('@/lib/config/sistema',()=>({obterConfiguracaoSistema:m.config,obterSofiaGlobalChannelConfig:m.global}));vi.mock('@/lib/horarios/verificar',()=>({verificarHorarioAtendimento:m.hours}));vi.mock('@/lib/whatsapp/contact-status',()=>({processarStatusContatoInbound:m.contact}));vi.mock('@/lib/whatsapp/sofia-control',()=>({resolveWhatsAppInboundConversation:m.resolve}));vi.mock('@/lib/whatsapp/inbound-normalizer',()=>({normalizarMensagemEvolution:m.normalize}));vi.mock('@/lib/whatsapp/action-router',()=>({processarAcaoInterativaWhatsApp:m.actionRouter}))
import {POST} from '@/app/api/webhooks/evolution/route'
function db(existing=false,lastIaMsg:any=null){const calls:string[]=[];const client:any={storage:{from:vi.fn()},rpc:vi.fn(),from:vi.fn((table:string)=>{let isIaQuery=false;const b:any={select:vi.fn(()=>b),eq:vi.fn((col,val)=>{if(col==='remetente'&&val==='ia')isIaQuery=true;return b}),order:vi.fn(()=>b),limit:vi.fn(()=>b),insert:vi.fn(()=>{calls.push(`persist:${table}`);return b}),maybeSingle:vi.fn(async()=>{if(table==='mensagens'){if(isIaQuery)return{data:lastIaMsg,error:null};return{data:existing?{id:'message-1'}:null,error:null}}return{data:{id:'client-1'},error:null}}),single:vi.fn(async()=>({data:{id:'message-1'},error:null}))};return b})};return{client,calls}}
const req=(text='hello')=>new Request('https://test/api/webhooks/evolution',{method:'POST',headers:{'x-webhook-secret':'secret'},body:JSON.stringify({event:'messages.upsert',data:{key:{id:'evo-1',fromMe:false,remoteJid:'5541999990003@s.whatsapp.net'},message:{conversation:text}}})})
beforeEach(()=>{vi.clearAllMocks();vi.unstubAllEnvs();m.config.mockImplementation(async(k:string)=>k==='EVOLUTION_WEBHOOK_SECRET'?'secret':null);m.global.mockResolvedValue({enabled:true});m.hours.mockResolvedValue({dentro:true});m.contact.mockResolvedValue({suprimirSofia:false});m.resolve.mockResolvedValue({conversaId:'conversation-1',iaAtiva:true});m.normalize.mockReturnValue(null);m.rag.mockResolvedValue(undefined);m.attach.mockResolvedValue(true);m.prompt.mockResolvedValue({success:true,messageId:'prompt-1'});m.actionRouter.mockResolvedValue({handled:true,catalog:{success:true}})})
describe('Evolution Sofia inbound batching producer',()=>{
 it.each([undefined,'false','TRUE',' true '])('defaults closed for %s',async value=>{const{client}=db();m.admin.mockReturnValue(client);if(value!==undefined)vi.stubEnv('SOFIA_INBOUND_BATCH_EVOLUTION_ENQUEUE_ENABLED',value);expect((await POST(req())).status).toBe(200);expect(m.attach).not.toHaveBeenCalled();expect(m.rag).toHaveBeenCalled()})
 it('attaches after persistence only for exact true',async()=>{const{client,calls}=db();m.admin.mockReturnValue(client);vi.stubEnv('SOFIA_INBOUND_BATCH_EVOLUTION_ENQUEUE_ENABLED','true');m.attach.mockImplementation(async()=>{calls.push('attach');return true});expect((await POST(req())).status).toBe(200);expect(calls).toEqual(['persist:mensagens','attach']);expect(m.attach).toHaveBeenCalledWith(expect.objectContaining({messageId:'message-1',conversationId:'conversation-1',customerId:'client-1',channel:'whatsapp'}));expect(m.rag).not.toHaveBeenCalled()})
 it('does not attach duplicates',async()=>{const{client}=db(true);m.admin.mockReturnValue(client);vi.stubEnv('SOFIA_INBOUND_BATCH_EVOLUTION_ENQUEUE_ENABLED','true');expect((await POST(req())).status).toBe(200);expect(m.attach).not.toHaveBeenCalled()})
 it('keeps intake and logs only a token on attach failure',async()=>{const{client}=db();m.admin.mockReturnValue(client);vi.stubEnv('SOFIA_INBOUND_BATCH_EVOLUTION_ENQUEUE_ENABLED','true');m.attach.mockResolvedValue(false);const error=vi.spyOn(console,'error').mockImplementation(()=>undefined);expect((await POST(req())).status).toBe(200);expect(error).toHaveBeenCalledWith('[Evolution Webhook] SOFIA_BATCH_ATTACH_FAILED');expect(m.rag).not.toHaveBeenCalled();error.mockRestore()})
})
     it.each(['cardápio','cardapio','menu','combos'])('sends exactly one catalog prompt for keyword %s without automation dispatch',async keyword=>{const{client}=db();m.admin.mockReturnValue(client);m.normalize.mockReturnValue({interactiveId:undefined});const response=await POST(req(`quero ver o ${keyword}`));expect(response.status).toBe(200);expect(m.prompt).toHaveBeenCalledTimes(1);expect(m.attach).not.toHaveBeenCalled();expect(m.rag).not.toHaveBeenCalled()})
     it('does not treat a substring as a catalog keyword',async()=>{const{client}=db();m.admin.mockReturnValue(client);m.normalize.mockReturnValue({interactiveId:undefined});await POST(req('menuzinho'));expect(m.prompt).not.toHaveBeenCalled()})
     it('delivers catalog cards when customer confirms with 1 after a recent prompt',async()=>{const{client}=db(false,{conteudo:'🔥 *Cardápio Oficial de Domingo*\n...',data_criacao:new Date().toISOString()});m.admin.mockReturnValue(client);m.normalize.mockReturnValue({interactiveId:undefined});const response=await POST(req('1'));expect(response.status).toBe(200);const body=await response.json();expect(body.status).toBe('catalog_cards_delivered');expect(m.actionRouter).toHaveBeenCalledWith(expect.objectContaining({interactiveId:'catalog:view'}));expect(m.attach).not.toHaveBeenCalled();expect(m.rag).not.toHaveBeenCalled()})
     it('does not treat 1 as catalog confirmation without a recent prompt',async()=>{const{client}=db(false,null);m.admin.mockReturnValue(client);m.normalize.mockReturnValue({interactiveId:undefined});const response=await POST(req('1'));expect(response.status).toBe(200);const body=await response.json();expect(body.status).not.toBe('catalog_cards_delivered');expect(m.actionRouter).not.toHaveBeenCalled()})
